"""
Django settings for MyProject2 project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7wfza5cnl!+1+nwakfd&@4ly0g16ecv0t!m+79t)xzhi#xvq0e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'CustomUserApp',
    'django_utils',
    'django_template_maths',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyProject2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [Path(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            
            ],
        },
    },
]

WSGI_APPLICATION = 'MyProject2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'bookdata',
#         'USER': 'cruduser',
#         'PASSWORD': 'Chetu@123',
#         'HOST': 'localhost',
#         'PORT': '5432'
#     }
# }

AUTH_USER_MODEL="CustomUserApp.CustomUser"

# 'ENGINE': 'django.db.backends.postgresql_psycopg2'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_URL = "/media/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE ='django.contrib.sessions.backends.db'
# SESSION_COOKIE_AGE = 30


#--------------For Email Verification------------------
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'abhisek0099977@gmail.com'
EMAIL_HOST_PASSWORD = 'kunvrzazjffulosu'
EMAIL_PORT = 587




AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

# stripe payment gateway integration
import stripe
STRIPE_PUBLIC_KEY = 'pk_test_51PduS7RqZgX2M2StxPw3TZNMvEqyvBYH19JG1vaKKwj9A7U2i32oRRwutj3F1RMPdIU9KsNdImAY7ywnL0DA5M4p000t7bZcFh'
STRIPE_SECRET_KEY = 'sk_test_51PduS7RqZgX2M2StxtscxtsUM63Pc6TRisNe3AWHTP7XmoSkyzOvFCu5lM7wRWrqSRwlTk0a1bUo5L0lAPhLNZe100Nykdq3vz'
stripe.api_key = "sk_test_51PduS7RqZgX2M2StxtscxtsUM63Pc6TRisNe3AWHTP7XmoSkyzOvFCu5lM7wRWrqSRwlTk0a1bUo5L0lAPhLNZe100Nykdq3vz"

# paypal payment gateway integration
# PAYPAL_CLIENT_ID = 'AQEn4I4aWO4l4jkoRmAth16f7XAKw5Fzpu8Et1ky3GrLUeSzLFNiJRwGrh_8zQwOoUdoqnju0Yf_SQXs'
# PAYPAL_SECRET_KEY = 'ELnSvOYpnGF17QhDTUT7exah_dC1JHOq0KJX5WIlo2NChMO8Y40L6AqSSEoIjIfXaxmMyBJSn_6IfGA5'