# Generated by Django 4.2.13 on 2024-07-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserApp', '0002_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
