# Generated by Django 4.2.13 on 2024-07-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserApp', '0003_delete_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
