# Generated by Django 4.2.13 on 2024-07-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserApp', '0005_order_item_name_order_price_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
