# Generated by Django 4.2.13 on 2024-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUserApp', '0006_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
